Firts pull req second to master
Bronzza/HomeWork9 pull request #1
Opened 2019-03-24 15:12 UTC by Bronzza

2019-03-24 19:02 UTC, Anderwerty requested changes
You make test code so difficult to read and support. It better to create separate test classes.

2019-03-24 19:02 UTC, Anderwerty commented on .idea/uiDesigner.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This file should be in the repository.

2019-03-24 19:02 UTC, Anderwerty commented on src/main/java/MyArrayList.java
> +public class MyArrayList<T> implements MyList<T> {
Please use some root package. Don't put classes just inti java package.

2019-03-24 19:02 UTC, Anderwerty commented on src/main/java/MyArrayList.java
> +    private final int DEFAULT_CAPACITY = 10;
It is not the right declaration.  You forget modifier static.

2019-03-24 19:02 UTC, Anderwerty commented on src/main/java/MyArrayList.java
> +
Remove redundant blank line.

2019-03-24 19:02 UTC, Anderwerty commented on src/main/java/MyArrayList.java
> +        for (int j = 0; j < array.length; j++) {
The complexity of your algorithm is O(N) but should be O(1).

2019-03-24 19:02 UTC, Anderwerty commented on src/main/java/MyArrayList.java
> +    private boolean checkIsExpand() {
Implementation is not right.

2019-03-24 19:02 UTC, Anderwerty commented on src/main/java/MyArrayList.java
> +    public void add(T t) {
What if counter>DEFAULT_CAPACITY? Do you have a test for this scenario?

2019-03-24 19:02 UTC, Anderwerty commented on src/main/java/MyArrayList.java
> +        if (index < 0 || index > counter) {
Is it ok if index=counter.?
Please move validation into a separate method and reuse it.

2019-03-24 19:02 UTC, Anderwerty commented on src/main/java/MyArrayList.java
> +
Remove redundant blank line.

2019-03-24 19:02 UTC, Anderwerty commented on src/main/java/MyArrayList.java
> +    public String toString() {
You could use Arrays.toString()

2019-03-24 19:02 UTC, Anderwerty commented on src/main/java/MyLinkedList.java
> +public class MyLinkedList<T> implements MyList<T> {
The same

2019-03-24 19:02 UTC, Anderwerty commented on src/main/java/MyLinkedList.java
> +            throw new IndexOutOfBoundsException();
Please add a test for this scenario.

2019-03-24 19:02 UTC, Anderwerty commented on src/main/java/MyLinkedList.java
> +            throw new IndexOutOfBoundsException();
The same

2019-03-24 19:02 UTC, Anderwerty commented on src/main/java/MyLinkedList.java
> +            throw new NullPointerException();
NullPointerException could be thrown by the code below. So it is better to create your own custom exception and throw it.

2019-03-24 19:02 UTC, Anderwerty commented on src/main/java/MyLinkedList.java
> +
Remove redundant blank lines.

2019-03-24 19:02 UTC, Anderwerty commented on src/main/java/MyList.java
> +public interface MyList<T> {
the same

2019-03-24 19:02 UTC, Anderwerty commented on src/main/java/MyStack.java
> +public class MyStack<T> extends MyLinkedList implements MyStackInterface <T> {
The same. And why don't use generic for MyLinkedList?

2019-03-24 19:02 UTC, Anderwerty commented on src/main/java/MyStack.java
> +
Remove the blank line.

2019-03-24 19:02 UTC, Anderwerty commented on src/main/java/MyStackInterface.java
> +public interface MyStackInterface <T> {
The same

2019-03-24 19:02 UTC, Anderwerty commented on src/main/java/MyStackInterface.java
> +
Remove redundant blank line.

2019-03-24 19:02 UTC, Anderwerty commented on src/test/java/MyLinkedListTest.java
> +import static org.junit.Assert.*;
Don't use wild cards in imports.

2019-03-24 19:02 UTC, Anderwerty commented on src/test/java/MyLinkedListTest.java
> +
Remove redundant blank lines.

2019-03-24 19:02 UTC, Anderwerty commented on src/test/java/MyLinkedListTest.java
> +
The same

2019-03-24 19:02 UTC, Anderwerty commented on src/test/java/MyStackTestAbstract.java
> +}
Add a blank line at the end of the file.

2019-03-24 19:02 UTC, Anderwerty commented on src/test/java/MyStackTest.java
> +}
Add a blank line at the end of the file.

2019-03-24 19:02 UTC, Anderwerty commented on src/test/java/MyStackTest.java
> +        assertEquals(Exception.class, myStack.pop());
This assert does not work. `assertEquals(Exception.class, myStack.pop());->myStack.pop();`

2019-03-24 19:02 UTC, Anderwerty commented on src/test/java/MyStackTest.java
> +        myStack.push(value);
Why you push only one element?

2019-03-24 19:02 UTC, Anderwerty commented on src/test/java/MyStackTest.java
> +        assertEquals(value,myStack.peek());
Please format your code.

2019-03-24 19:02 UTC, Anderwerty commented on src/test/java/MyStackTest.java
> +        myStack.peek();
Why you don't use assert for this line?

2019-03-24 19:02 UTC, Anderwerty commented on src/test/java/MyStackTest.java
> +        return "String";
`"String"` looks like a magic number. Please use a constant.

2019-03-24 19:02 UTC, Anderwerty commented on src/test/java/MyLinkedListTestAbstract.java
> +}
Please add a blank line at the end of the file.

2019-03-24 19:02 UTC, Anderwerty commented on src/test/java/MyLinkedListTest.java
> +    private int randomInt(int limit) {
How do you use this method?

2019-03-24 19:02 UTC, Anderwerty commented on src/test/java/MyArrayListTest.java
> +    public Integer createRandomValue() {
Test data should be static, not dynamic.

2019-03-25 14:16 UTC, Bronzza commented on src/main/java/MyArrayList.java
> +    private boolean checkIsExpand() {
What does it mean?  Is it about the method "checkIsExpand" or about toString?

2019-03-25 14:27 UTC, Anderwerty requested changes

2019-03-25 14:27 UTC, Anderwerty commented on src/main/java/MyArrayList.java
> +    private boolean checkIsExpand() {
Look where you use checklsExpand. First, you should check if there any empty place in the array to put new element. If no make your array bigger.

2019-03-25 15:05 UTC, Bronzza commented on src/main/java/MyStackInterface.java
> +public interface MyStackInterface <T> {
What means the same here, "Remove redundant blank line"?

2019-03-25 15:54 UTC, Bronzza commented on .idea/uiDesigner.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Couse of my gitIgnore I cant add it to the repository, how should I add this file?

2019-03-25 16:06 UTC, Anderwerty commented on .idea/uiDesigner.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Maybe first commit this file and then commit gitignore. Remove this file from the repo.

2019-03-25 16:13 UTC, Bronzza commented on src/main/java/MyArrayList.java
> +    public void add(T t) {
Should I use reflection in test method to assign value to counter more than to DEFAULT_CAPACITY? Couse in other case this situation will never happen.

2019-03-25 16:14 UTC, Bronzza commented on src/main/java/MyArrayList.java
> +    public String toString() {
In this case in output will see null objects wich are stored in inner array of the class

2019-03-25 16:16 UTC, Bronzza commented on src/main/java/MyLinkedList.java
> +            throw new IndexOutOfBoundsException();
There are two tests in "@Test add1()" for invalid index, for negative index and for index that is out of list size range, which both expect indexOutOfBoundExceptions

2019-03-25 16:17 UTC, Anderwerty commented on src/main/java/MyArrayList.java
> +    public void add(T t) {
no, you should not.

2019-03-25 16:18 UTC, Bronzza commented on src/test/java/MyStackTest.java
> +        assertEquals(Exception.class, myStack.pop());
Pop moves you to remove in MyLinkedList which moves you to method “unlink” from there to method “FindElemnt” which throws an exception which is cathced by assert -> works this way. Removing "(expected = IndexOutOfBoundsException.class)"text from the annotation will lead to fail the test

2019-03-25 16:20 UTC, Bronzza commented on src/main/java/MyArrayList.java
> +    private boolean checkIsExpand() {
public void add(T t) {
        array[counter] = t;
        counter++;
In this method counter is incremented after addition, so it point out on next field of array (after last added element). That is why we check counter and size for "==". Method works.

2019-03-25 16:20 UTC, Anderwerty requested changes

2019-03-25 16:20 UTC, Anderwerty commented on src/main/java/MyLinkedList.java
> +            throw new IndexOutOfBoundsException();
ok

2019-03-25 16:20 UTC, Anderwerty commented on src/main/java/MyStackInterface.java
> +public interface MyStackInterface <T> {
No put all classes into some root package

2019-03-25 16:38 UTC, Anderwerty requested changes

2019-03-25 16:38 UTC, Anderwerty commented on src/test/java/MyArrayListTest.java
> +    private int indexTest;
Why not constant here?

2019-03-25 16:38 UTC, Anderwerty commented on src/test/java/MyStackTest.java
> +        assertEquals(Exception.class, myStack.pop());
assert does not catch an exception

2019-03-25 16:55 UTC, Anderwerty approved these changes
Remove files that should not be in a repo.

2019-06-26 08:27 UTC, merged